export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_FILTER = 'SET_FILTER';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_RESTAURANT = 'SET_RESTAURANT';
export const SET_DISH = 'SET_DISH';